apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
spec:
  type: ClusterIP
  selector:
    app: mariadb
  ports:
  - protocol: TCP
    port: 3306
    #nodePort: 30306
    targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: my-server-service
spec:
  type: NodePort
  selector:
    app: my-server
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: front-end-service
spec:
  type: NodePort
  selector:
    app: front-end
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30080